import type { Metadata } from "next";
import { Manrope, IBM_Plex_Sans } from "next/font/google";
import "../globals.css";
import Navigation from "@/sections/navigation";
import Footer from "@/sections/footer";
import Cta from "@/sections/cta";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const plexSans = IBM_Plex_Sans({
  variable: "--font-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${plexSans.variable} antialiased font-plex-sans select-none`}
      >
        <Navigation />
        <div className=" min-h-screen">
          {children}
        </div>
        <Cta />
        <Footer />
      </body>
    </html>
  );
}
